#!/bin/bash

# DreamHost Deployment Script for SharePoint to Dropbox Video Bridge
# Usage: ./deploy-dreamhost.sh

set -e

echo "🚀 Preparing SharePoint to Dropbox Video Bridge for DreamHost deployment..."

echo ""
echo "📝 Pre-deployment checklist:"
echo "1. Have you configured your .env file with all required credentials?"
echo "2. Have you tested the application locally?"
echo "3. Do you have SSH access to your DreamHost server?"
echo "4. Have you noted your DreamHost paths?"
echo ""
read -p "Press Enter to continue or Ctrl+C to cancel..."

echo ""
echo "📦 Files ready for deployment:"
echo "   - app.py (Flask application)"
echo "   - passenger_wsgi.py (Passenger WSGI entry point)"
echo "   - .htaccess (Apache configuration)"
echo "   - requirements.txt (Python dependencies)"
echo "   - templates/ (HTML templates)"
echo "   - .env (environment variables - MUST be uploaded separately)"
echo ""
echo "⚠️  IMPORTANT:"
echo "   - DO NOT commit .env to git"
echo "   - Upload .env separately via SFTP"
echo "   - Update .htaccess with your actual DreamHost paths"
echo ""
echo "📝 Next steps:"
echo "1. SSH into your DreamHost server:"
echo "   ssh videobridge@yourserver.dreamhost.com"
echo ""
echo "2. Navigate to your web directory:"
echo "   cd /home/videobridge/videobridge.roblog.com"
echo ""
echo "3. Upload files (via git or SFTP):"
echo "   git clone https://github.com/robroyaus/SharePointVideoLinker.git ."
echo "   OR use SFTP to upload files"
echo ""
echo "4. Install Python dependencies:"
echo "   pip3 install --user -r requirements.txt"
echo ""
echo "5. Upload .env file via SFTP (DO NOT use git)"
echo ""
echo "6. Update .htaccess with correct paths:"
echo "   Edit PassengerAppRoot line"
echo ""
echo "7. Restart Passenger:"
echo "   mkdir -p tmp && touch tmp/restart.txt"
echo ""
echo "8. Test basic authentication:"
echo "   Use credentials from APP_USERNAME and APP_PASSWORD in .env"
echo ""
echo "🎉 Ready for deployment!"
